version: '3.9'
services:
  # Database service begin
  database:
    container_name: todos_db
    image: "postgres:13"
    volumes:
      - todo-storage:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
    restart: unless-stopped
  # Database service end
  # --- 
  # Web service begin
  web:
    build: .
    command: gunicorn todos.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - staticfiles:/app/staticfiles/
    expose:
      - 8000
    depends_on:
      - database
    restart: unless-stopped
    env_file:
      - ./.env
  # Web service end
  # nginx begin
  nginx: # Our reverse proxy proxying request and serving statics
    build: ./nginx
    volumes:
      - staticfiles:/app/staticfiles/
    ports:
      - 8000:80 # map host 8080 to nginx 80 on which it listen's to
    depends_on:
      - web # strongly depends on web
  # nginx end

volumes:
  todo-storage:
  staticfiles:  