# Generated by Django 4.1.5 on 2023-01-07 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TodoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todo', models.TextField(help_text='Todo name', max_length=80, unique=True)),
                ('completed', models.BooleanField(default=False, help_text='Is completed?')),
                ('deadline', models.DateTimeField()),
            ],
        ),
    ]
